### ISSUE TITLE
help to recover from java.net.ConnectException: https://auth.sphere.io:443

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1142]
```
java.util.concurrent.CompletionException: io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem.
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_60]
Caused by: io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem.
    at io.sphere.sdk.http.HttpClientAdapterBase.lambda$execute$12(HttpClientAdapterBase.java:50) ~[sdk-http-1.0.0-RC3.jar:na]
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[na:1.8.0_60]
Caused by: java.util.concurrent.CompletionException: io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem.
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_60]
Caused by: io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem.
    at io.sphere.sdk.http.DefaultAsyncHttpClientAdapterImpl$1.onThrowable(DefaultAsyncHttpClientAdapterImpl.java:45) ~[sdk-http-ahc-1_9-1.0.0-RC3.jar:na]
    at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:238) ~[async-http-client-1.9.33.jar:na]
    at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137) ~[async-http-client-1.9.33.jar:na]
    at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145) ~[async-http-client-1.9.33.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.5.Final.jar:na]
Caused by: java.net.ConnectException: https://auth.sphere.io:443
    at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133) ~[async-http-client-1.9.33.jar:na]
    at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145) ~[async-http-client-1.9.33.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400) ~[netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.5.Final.jar:na]
```

**Comment by schleichardt** [comment]
see also
* https://github.com/AsyncHttpClient/async-http-client/issues/934
* https://groups.google.com/forum/#!topic/asynchttpclient/pSxiChVJwiI

**Comment by schleichardt** [comment]
this was observed with an old SDK version with an old HTTP client

**Comment by schleichardt** [comment]
cannot reproduce

**Comment by dust1973** [comment]
Hello, I have the problem on my local computers. I have set up a test system locally(Localhost). Last week everything worked fine. I wanted to customize a few things, I've compiled my code new and come this error.
"io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem." I have:

- commercetools-convenience-1.0.0.jar, 
- commercetools-java-client-ahc-2_0-1.0.0.jar
- commercetools-java-client-core-1.0.0.jar
- commercetools-sdk-base-1.0.0.jar

**Comment by dust1973** [comment]
httpClient: DefaultAsyncHttpClient2_0AdapterImpl[asyncHttpClient=org.asynchttpclient.DefaultAsyncHttpClient@5df4762a,threadPool=java.util.concurrent.ForkJoinPool@4e909f0b[Running, parallelism = 4, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]]

**Comment by dust1973** [comment]
userAgent: AHC/2.0
threadPoolName: AsyncHttpClient

**Comment by acbeni** [comment]
Hi @dust1973, as a solution 0 can you update 1.29.1, there might be already a fix, yet if the problem persists, can you upload a sample project so i can take a look.
