### ISSUE TITLE
java.lang.NoSuchMethodError error when calling client.executeBlocking(sphereRequest)

### ISSUE THREAD

**Issue by ramysalama** [commercetools/commercetools-jvm-sdk#1851]
Hi,
I'm getting the following error with the new version (1.37.0) of the SDK, when calling client.executeBlocking(sphereRequest), my code can run with versions 1.35.0 & 1.36.0

> 2018-12-05 14:22:05.702  WARN 3105 --- [pool-5-thread-1] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by org.asynchttpclient.netty.request.NettyRequestSender$1.operationComplete()
java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:111) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:83) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:33) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:156) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at org.asynchttpclient.netty.request.NettyChannelConnector.connect0(NettyChannelConnector.java:81) ~[async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.netty.request.NettyChannelConnector.connect(NettyChannelConnector.java:69) ~[async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.netty.request.NettyRequestSender$1.onSuccess(NettyRequestSender.java:292) ~[async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.netty.request.NettyRequestSender$1.onSuccess(NettyRequestSender.java:285) ~[async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:24) ~[async-http-client-2.0.38.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:33) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:285) [async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:136) [async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:107) [async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:216) [async-http-client-2.0.38.jar:na]
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:184) [async-http-client-2.0.38.jar:na]
	at io.sphere.sdk.http.DefaultAsyncHttpClient2_0AdapterImpl.executeDelegate(DefaultAsyncHttpClient2_0AdapterImpl.java:23) [sdk-http-ahc-2_0-1.37.0.jar:na]
	at io.sphere.sdk.http.HttpClientAdapterBase.execute(HttpClientAdapterBase.java:39) [commercetools-sdk-base-1.37.0.jar:na]
	at io.sphere.sdk.client.TokensSupplierImpl.get(TokensSupplierImpl.java:54) [commercetools-java-client-core-1.37.0.jar:na]
	at io.sphere.sdk.client.AuthActor.process(AuthActor.java:52) [commercetools-java-client-core-1.37.0.jar:na]
	at io.sphere.sdk.client.Actor$ReceiveBuilder.when(Actor.java:45) ~[commercetools-java-client-core-1.37.0.jar:na]
	at io.sphere.sdk.client.AuthActor.receive(AuthActor.java:41) [commercetools-java-client-core-1.37.0.jar:na]
	at io.sphere.sdk.client.Actor.lambda$tell$0(Actor.java:17) ~[commercetools-java-client-core-1.37.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

**Comment by acbeni** [comment]
Hi Rami, 

I think you are using `sdk-http-ahc-2_0` in your dependencies, if its the case, replace it by `sdk-http-ahc-2_5` and see if it performs fine.

**Comment by acbeni** [comment]
Hi @ramysalama , since i had no feedback from your side i ll close the issue, feel free to open it with a comment of what's going wrong if it's still not working correctly.

**Comment by marcinwaldowski** [comment]
This issue occur also for version 1.46.0.

```
<dependency>
   <groupId>com.commercetools.sdk.jvm.core</groupId>
   <artifactId>commercetools-models</artifactId>
   <version>1.46.0</version>
</dependency>
<dependency>
   <groupId>com.commercetools.sdk.jvm.core</groupId>
   <artifactId>commercetools-java-client</artifactId>
   <version>1.46.0</version>
</dependency>
```

To make it work additional dependency is needed:

```
<dependency>
   <groupId>com.commercetools.sdk.jvm.core</groupId>
   <artifactId>sdk-http-ahc-2_5</artifactId>
   <version>1.46.0</version>
</dependency>
```
