### ISSUE TITLE
JVM SDK Error AutoRefreshSphereAccessTokenSupplierImpl

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-jvm-sdk#2176]
io.sphere.sdk.client.AutoRefreshSphereAccessTokenSupplierImpl.lambda$supervisedTokenSupplier$2(AutoRefreshSphereAccessTokenSupplierImpl.java:51)
at io.sphere.sdk.retry.AsyncRetrySupervisorImpl.forceApply(AsyncRetrySupervisorImpl.java:99)
at io.sphere.sdk.retry.AsyncRetrySupervisorImpl.retry(AsyncRetrySupervisorImpl.java:85)

https://jira.commercetools.com/browse/SUPPORT-13682

**Comment by jenschude** [comment]
Released a patch for 1.64.1 which prevents the retry loop in case the HttpClient has been closed
